#WIP (Work In Progress)
openapi: 3.0.2
info:
  title: Inventory API
  version: 1.0.0
  description: An API for managing the Inventory Databases.

servers:
  - url: https://ykold98ku7.execute-api.eu-north-1.amazonaws.com/dev
    description: The base URL.

paths:
  /inventory/{itemId}:
    get:
      summary: Returns total amount per item id.
      parameters:
        - in: path
          name: itemId
          schema:
            type: string
          required: true
          description: String ID of the item to get.
      responses:
        '200':
          description: A JSON object of Inventory Item.
          content:
            application/json:
            schema:
              type: object
              properties:
                itemId:
                  type: string
                  example: item id
                amount:
                  type: string
                  example: 42
                site:
                  type: string
                  example: random string
        '400':
          description: The specified Item ID is invalid (not a number).
        '404':
          description: An item with the specified ID was not found.
        default:
          description: Unexpected error
  /inventory/create/{itemId}:
    post:
      summary: Creates a new Inventory item for all sites.
      parameters:
        - in: path
          name: itemId
          schema:
            type: string
          required: true
          description: String ID for item to create.
      requestBody:
        description: Optional description in *Markdown* #fix
        required: true
        content:
          application/json:
            #schema:
              #$ref: '#/components/schemas/Pet' #fix
      responses:
        '201':
          description: Created
  /inventory/delete/{itemId}:
    post:
      summary: Deletes the given item by enabling the deleted flag on. API usage of item is disabled until item deleted flag is turned off.
      parameters:
        - in: path
          name: itemId
          schema:
            type: string
          required: true
          description: String ID of the item to delete.
      requestBody:
        description: Optional description in *Markdown* #fix
        required: true
        content:
          application/json:
            #schema:
              #$ref: '#/components/schemas/Pet' #fix
      responses:
        '200':
          description: A JSON object of deleted Inventory Item.
          content:
            application/json:
            schema:
              type: object
              properties:
                amount:
                  type: string
                  example: 86
                deleted:
                  type: bool
                  example: true
                modelNumber:
                  type: string
                  example: H2
                site:
                  type: string
                  example: FIN_H1
        '400':
          description: Model Number or site does not exist.
        '500':
          description: Could not update flag.
        default:
          description: Unexpected error
  /inventory/reactivate/{itemId}:
    post:
      summary: Turns deleted flag off and reactivates the given item.
      parameters:
        - in: path
          name: itemId
          schema:
            type: string
          required: true
          description: String ID of the item to reactivate.
      requestBody:
        description: Optional description in *Markdown* #fix
        required: true
        content:
          application/json:
            #schema:
              #$ref: '#/components/schemas/Pet' #fix
      responses:
        '200':
          description: A JSON object of reactivated Inventory Item.
          content:
            application/json:
            schema:
              type: object
              properties:
                amount:
                  type: string
                  example: 86
                deleted:
                  type: bool
                  example: false
                modelNumber:
                  type: string
                  example: H2
                site:
                  type: string
                  example: FIN_H1
        '400':
          description: Model Number or site does not exist.
        '500':
          description: Could not update flag.
        default:
          description: Unexpected error
  /inventory/amount:
    post:
      summary: Updates the amount of given item id to specified site.
      requestBody:
        description: Optional description in *Markdown* #fix
        required: true
        content:
          application/json:
            #schema:
              #$ref: '#/components/schemas/Pet' #fix
      responses:
#        '200':
#          description: A JSON object of deleted Inventory Item.
#          content:
#            application/json:
#            schema:
#              type: object
#              properties:
#                amount:
#                  type: string
#                  example: 86
#                deleted:
#                  type: bool
#                  example: true
#                modelNumber:
#                  type: string
#                  example: H2
#                site:
#                  type: string
#                  example: FIN_H1
        '400':
          description: #fix
        '500':
          description: #fix
  /inventory/site/{itemId}:
    get:
      summary: Returns the given item amount for all sites.
      parameters:
        - in: path
          name: itemId
          schema:
            type: string
          required: true
          description:
      responses:
  # Admin path
  /inventory/add/{itemId}:
    post:
      summary: Admin function that creates a new item to a specific site.
      parameters:
        - in: path
          name: itemId
          schema:
            type: string
          required: true
          description: String ID of the item to create for a specific site.
      responses:
  /site/{siteId}:
    get:
      summary: Returns site specific information for given site id.
      parameters:
        - in: path
          name: siteId
          schema:
            type: string
          required: true
          description: String ID of the site to get.
      responses:
        '200':
          description: A JSON object of Inventory Item.
          content:
            application/json:
            schema:
              type: object
              properties:
                siteID:
                  type: string
                  example: FIN_H1
                siteName:
                  type: string
                  example: Helsinki
                address:
                  type: string
                  example: StreetName 42
        '400':
          description: The specified site ID is invalid (not a number).
        '404':
          description: A site with the specified ID was not found.
        default:
          description: Unexpected error
  /site/create:
    post:
      summary: Admin function that creates a new site.
      responses:
        '201':
          description: Created
  /site/delete/{siteId}:
    post:
      summary: Deletes the given site by enabling the deleted flag on. API usage of site is disabled until site deleted flag is turned off.
      parameters:
        - in: path
          name: itemId
          schema:
            type: string
          required: true
          description: String ID of the site to delete.
      responses:
        '200':
          description: A JSON object of deleted site.
          content:
            application/json:
            schema:
              type: object
              properties:
                siteID:
                  type: string
                  example: FIN_H1
                address:
                  type: string
                  example: StreetName 42
                deleted:
                  type: bool
                  example: true
                siteName:
                  type: string
                  example: Helsinki
        '400':
          description: The specified site ID is invalid (not a number).
        '500':
          description: Could not update flag.
        default:
          description: Unexpected error
  /site/reactivate/{siteId}:
    post:
      summary: Turns deleted flag off and reactivates the given site.
      parameters:
        - in: path
          name: itemId
          schema:
            type: string
          required: true
          description: String ID of the site to reactivate.
      responses:
        '200':
          description: A JSON object of reactivated site.
          content:
            application/json:
            schema:
              type: object
              properties:
                siteID:
                  type: string
                  example: FIN_H1
                address:
                  type: string
                  example: StreetName 42
                deleted:
                  type: bool
                  example: false
                siteName:
                  type: string
                  example: Helsinki
        '400':
          description: The specified site ID is invalid (not a number).
        '500':
          description: Could not update flag.
        default:
          description: Unexpected error
