# serverless.yml

service: Inventory-API

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-north-1

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'